# Generated by Django 5.2.4 on 2025-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=1000, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
