name: Django CI/CD Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run flake8
        run: poetry run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
# Попытка запустить Postgres
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: 'drf'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: '260439'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -

    - name: Cache Poetry
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        poetry install
# Попытка дождаться полной загрузки Postgres
    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }}
          if [ $? -eq 0 ]; then
            echo "PostgreSQL is ready"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 1
        done
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Run migrations
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        # Подклюяение базы
#        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}
        DB_NAME: 'drf'
        DB_USER: 'postgres'
        DB_PASSWORD: '260439'
        DB_HOST: localhost

      run: poetry run python manage.py migrate

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        # Подклюяение базы
#        DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}
        DB_NAME: 'drf'
        DB_USER: 'postgres'
        DB_PASSWORD: '260439'
        DB_HOST: localhost
      run: poetry run python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/babushkin/dcd
          git init
          git remote set-url origin https://github.com/a-babushkin/drf_to_remote_server.git
          git fetch origin
          git checkout feature/Remote-server
          cp /home/babushkin/dcd/rezerv/docker-compose.yml /home/babushkin/dcd
          cp /home/babushkin/dcd/rezerv/nginx.conf /home/babushkin/dcd
          docker-compose down
          docker-compose up -d --build
          docker-compose exec web poetry run python manage.py migrate
